rtotal = 1560.0e3                       # radius in [m]
delta_r = 1000.0                        # step size in [m]
M_observed = 479.7e20                   # mass of Europa in [kg]
M_uncertainty = 1.5e20                  # kg
inertia_observed = 0.346                # observed moment of inertia taken from the planetary database
inertia_uncertainty = 0.005     
meanDensity_observed = 3013.0           # kg/m3
meanDensity_uncertainty = 1.7           # kg/m3
G = 6.67430e-11                         # gravitational constant
core_boundary = 700.0e3                 # initial core radius in [m]
mantle_boundary = 1400.0e3              # initial distance from center to mantle-crust/ocean boundary in [m]
ocean_boundary = 0                      # initial distance from centre to ocean-shell boundary in [m]
core_temp_min = 1073.0                  # minimum centre temperature in [K]
core_temp_mean = 1447.0                 # mean centre temperature in [K]
core_temp_max = 1750.0                  # maximum centre temperature in [K]
surface_temp = 104.0                    # surface temperature in [K]
core_alpha = 87.0e-6                    # thermal expansivity of the core in [K^-1]
mantle_alpha = 40.0e-6                  # thermal expansivity of the mantle in [K^-1]
shell_alpha = -4.93e-8                  # thermal expansivity of the ocean/shell in [K^-1]
ice_alpha = 0                           # thermal expansivity of the ice crust in [K^-1]
core_K = 75.2e9                         # bulk modulus of the core in [Pa]
mantle_K = 130.0e9                      # bulk modulus of the mantle in [Pa]
shell_K = 1.056e10                      # bulk modulus of the shell/ocean in [Pa]
ice_K = 0                               # bulk modulus of the ice crust in [Pa]
density_core_FeS = 5500.0
density_core_Fe = 7874.0
density_mantle = 3300.0
density_shell = 1000.0

# EARTH VALUES FOR VALIDATION
rtotal_Earth = 6378.0e3
M_observed_Earth = 59742.0e20
meanDensity_observed_Earth = 5513.0
inertia_observed_Earth = 0.331
core_boundary_Earth = 3450.0e3           # initial core radius in [m]
mantle_boundary_Earth = 6320.0e3        # initial distance from center to mantle-crust boundary in [m]
core_density_Earth = 11500.0            # kg/m3
mantle_density_Earth = 4500.0
crust_density_Earth = 2600.0